name: Utils
main: io.rampant.bukkit.utils.Utils
version: 3.0
commands:
  who:
    description: Lists the currently connected players.
  motd:
    description: Displays the Server's Message of the Day.
  rules:
    description: Displays the Server's rules.
  utils:
    description: Manage Utilities.
    usage: |
           /<command> reload - Reload utilities settings.